usuario@ubuntu:~/tdd$ rspec -I. spec/punto_spec.rb FF
Failures:

  1) Punto probando los getters y el to_s se ha de poder instanciar un
punto
     Failure/Error: expect(@origen.x).to eq(0)

     NoMethodError:
       undefined method `x' for nil:NilClass
     # ./spec/punto_spec.rb:6:in `block (3 levels) in <top (required)>'

  2) Punto probando los getters y el to_s el método to_s funciona bien
     Failure/Error: expect(@origen.to_s).to eq("(0,0)")

       expected: "(0,0)"
            got: ""

       (compared using ==)
     # ./spec/punto_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.03328 seconds (files took 0.25179 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/punto_spec.rb:5 # Punto probando los getters y el to_s se
ha de poder instanciar un punto
rspec ./spec/punto_spec.rb:9 # Punto probando los getters y el to_s el
método to_s funciona