usuario@ubuntu:~/tdd$ rspec -I. spec/punto_spec.rb ..F
Failures:

  1) Punto probando los métodos de instancia se puede multiplicar por un
escalar
     Failure/Error: expect((unidad * 5).to_s).to eq("(5,5)")

     NoMethodError:
       undefined method `*' for #<Punto:0x000055f8b867cd78 @x=1, @y=1>
     # ./spec/punto_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 0.00469 seconds (files took 0.15346 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/punto_spec.rb:19 # Punto probando los métodos de instancia
se puede multiplicar por un escalar